services:
  - type: web
    name: psau-portal
    env: node
    region: frankfurt
    branch: psauportal
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: BREVO_HOST
        value: smtp-relay.brevo.com
      - key: BREVO_PORT
        value: "465"
      - key: BREVO_USER
        value: ac7177001@smtp-brevo.com
      - key: BREVO_PASS
        value: dY2tVIw1zh3kFDRE
      - key: BREVO_FROM
        value: PSAU Portal <abdulazizsowaankau@gmail.com>
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
